app/models/question_tag.rb
app/models/tag.rb
db/migrate/20170205132524_create_tags.rb
db/migrate/20170205132643_create_question_tags.rb
db/schema.rb
test/fixtures/question_tags.yml
test/fixtures/tags.yml
test/models/question_tag_test.rb
test/models/tag_test.rb

- Tagモデル 及び
- 中間テーブルのQuestionTagモデル作成

【タグ機能】モデル作成 issues/#4

---

.gitignore
Gemfile
Gemfile.lock

- 適当に選びました。他に欲しいものありましたらどんどん追加してください。

必要なGemインストール issues/#2

---

app/models/favorite.rb
db/migrate/20170205133046_create_favorites.rb
test/fixtures/favorites.yml
test/models/favorite_test.rb

【お気に入り機能】モデル作成 issues#5

---

app/models/question.rb
db/migrate/20170129075121_create_questions.rb
db/schema.rb
test/fixtures/questions.yml
test/models/question_test.rb

- user_id
- title
- content
お手すきでreviewをお願い致します

【質問機能】モデル作成 issues/#8

---

app/models/contribute.rb
db/migrate/20170216141152_create_contributes.rb
spec/factories/contributes.rb
spec/models/contribute_spec.rb

【貢献度機能】モデル作成 issues/#3

---

app/assets/javascripts/favorites.coffee
app/assets/stylesheets/favorites.scss
app/controllers/favorites_controller.rb
app/helpers/favorites_helper.rb
app/views/favorites/index.html.erb
config/routes.rb
spec/controllers/favorites_controller_spec.rb
spec/helpers/favorites_helper_spec.rb
spec/views/favorites/index.html.erb_spec.rb

- お気に入り一覧を 作成
- URLは/users/[ユーザーID]/favorites/[お気に入りID]
- 質問タイトルのみ表示
- 質問タイトルのリンクはダミー

【お気に入り】ユーザ毎のお気に入り一覧表示 issues/#23

---

app/models/answer.rb
db/migrate/20170304080439_create_answers.rb
spec/factories/answers.rb
spec/models/answer_spec.rb

【回答機能】モデル作成

---

config/routes.rb

【その他】ログイン画面に遷移できない事象の対応 issues/#43

---

db/seeds.rb

- 質問機能のシードデータを100件作成
- ユーザーIDは1〜50のランダムな値
- タイトル, 内容はダミーテキスト

【質問機能】シードデータ準備 issues/#15

---

app/models/question.rb
app/models/tag.rb

- あるQuestionに紐づくTagを全て取得できるようにする。
- あるTagに紐づくQuestionを全て取得できるようにする。

【タグ機能】質問とタグを多対多の関係にする issues/#51

---

db/seeds.rb

- タグは以下を作成
"ruby", "java", "php", "python", "ruby-on-rails", "postgresql",
"mysql", "sql", "git", "github", "gem", "html", "javascript",
"jquery", "ajax", "css", "bootstrap", "json", "http"
- 各Questionに対し上記の中から1〜5個のタグを紐付け

【タグ機能】シードデータ準備 issues/#12

---

app/controllers/answers_controller.rb
app/models/answer.rb

#25 
add answer destroy action

【Fixed】【回答機能】削除アクション #25

---

app/assets/javascripts/tag.coffee
app/assets/stylesheets/tag.scss
app/controllers/tag_controller.rb
app/helpers/tag_helper.rb
app/views/tag/index.html.erb
app/views/tag/show.html.erb
config/routes.rb
spec/controllers/tag_controller_spec.rb
spec/helpers/tag_helper_spec.rb

- タグの一覧表示
- タグにひもづく質問を表示
画面デザインについては別途対応したいと思います。

【タグ機能】タグで質問を検索できる issues/#17

---

app/assets/stylesheets/common.css
app/controllers/favorites_controller.rb
app/controllers/ranks_controller.rb
app/views/favorites/index.html.erb
app/views/ranks/index.html.erb
app/views/shared/_question.html
app/views/tag/show.html.erb

以下のデザインにしてみました。
「ここはおかしい」「ここはこうした方がいい」等がございましたらご指摘お願いします。

【共通】Questionを一覧表示する部分テンプレートを作成 Issues/#57

---

app/assets/stylesheets/tag.scss
app/views/tag/index.html.erb

以下のデザインにしてみました。
「ここはおかしい」「ここはこうした方がいい」等がございましたらご指摘お願いします。

【タグ機能】タグ一覧のデザイン変更 issues/#58

---

app/models/answer.rb
app/models/question.rb
app/models/user.rb
app/views/users/show.html.erb

質問、回答、ユーザーそれぞれからContributeを取得
- 質問のContributeはq_pointsで取得
- 回答のContributeはa_pointsで取得
- ユーザーのContributeはq_points, a_pointsで取得

【貢献度機能】 ユーザー毎に貢献度を取得できるようにする issues/#24

---

db/seeds.rb

-   質問に対する貢献度(1人Userあたり最大8件)
-   回答に対する貢献度(1人Userあたり最大8件)
(現時点では回答のシードデータが存在しないので作成されない)

【貢献度機能】シードデータ準備 issues/#24

---

app/controllers/questions_controller.rb
app/views/answers/_index.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
app/views/users/show.html.erb

#20 
ユーザーと質問に関係するViewも合わせて調整しています。

【質問機能】ユーザーと質問が紐付いている #20

---

db/seeds.rb

【回答機能】シードデータ準備 #14

---

app/assets/stylesheets/questions.scss
app/assets/stylesheets/scaffolds.scss
app/models/question.rb
app/views/questions/_form.html.erb
app/views/questions/edit.html.erb
app/views/questions/index.html.erb
app/views/questions/new.html.erb
app/views/questions/show.html.erb
app/views/users/show.html.erb

#34
CSSやリンク等、
違和感を感じた部分全体的に調整しました。

【共通】Viewの微調整 #34

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/users/index.html.erb

【全体】トップページに各画面へのメニュー #68

---

app/assets/stylesheets/normalize.css
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/answers/_index.html.erb
app/views/users/show.html.erb

【ユーザー機能】マイページで自分で投稿した質問、回答が見ることができる #74

---

app/views/users/show.html.erb

【ユーザー機能】マイページの見出しレベルのずれ調整 #80

---

config/environments/production.rb

【ユーザー機能】メール認証機能
